# Generated by Django 4.1 on 2022-08-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verses',
            name='text',
            field=models.CharField(max_length=5000),
        ),
    ]
